name: intake-gpd-blog
channels:
  - conda-forge
dependencies:
  - python=3.9
  - intake-geopandas
  - intake-pattern-catalog
  - pyarrow
  - ruamel.yaml
  # JupyterLab extensions
  - jupyterlab
  - dask-labextension
